/* Weather-Flip app (fullscreen downshift + expanded weather animations) */
const STORAGE_KEY='weather_flip_zip',REFRESH_MS=6e5,DEFAULT_ZIP='10001';
window.setupClock=function(t){const e=e=>String(e).padStart(2,'0'),n=()=>{const n=new Date;t.value=[e(n.getHours()),e(n.getMinutes()),e(n.getSeconds())];const o=document.getElementById('sr-time');o&&(o.textContent=t.value.join(':'))};n(),Tick.helper.interval(n,1e3)};
const elLoc=document.getElementById('location'),elTemp=document.getElementById('temp'),elCond=document.getElementById('condition'),elIcon=document.getElementById('icon'),form=document.getElementById('zipForm'),input=document.getElementById('zipInput'),statusEl=document.getElementById('status'),fullscreenBtn=document.getElementById('fullscreenBtn'),themeBtn=document.getElementById('themeBtn'),geoBtn=document.getElementById('geoBtn');
const setStatus=(t,e='')=>{statusEl.className='status '+e,statusEl.textContent=t||''};function saveZip(t){try{localStorage.setItem(STORAGE_KEY,t)}catch{}}function loadZip(){try{return localStorage.getItem(STORAGE_KEY)||DEFAULT_ZIP}catch{return DEFAULT_ZIP}}
async function fetchWeatherByZip(t){if(!window.WEATHER_API_KEY)throw new Error('NO_KEY');const e=`https://api.openweathermap.org/data/2.5/weather?zip=${encodeURIComponent(t)},US&appid=${window.WEATHER_API_KEY}&units=imperial`,n=await fetch(e);if(!n.ok)throw await buildHttpError(n);return n.json()}
async function fetchWeatherByCoords(t,e){if(!window.WEATHER_API_KEY)throw new Error('NO_KEY');const n=`https://api.openweathermap.org/data/2.5/weather?lat=${t}&lon=${e}&appid=${window.WEATHER_API_KEY}&units=imperial`,o=await fetch(n);if(!o.ok)throw await buildHttpError(o);return o.json()}
async function buildHttpError(t){const e=await t.text(),n=t.status,o=new Error('HTTP_'+n);return o.httpStatus=n,o.body=e,o}
function applyWeather(t){const{ name:e,main:n,weather:o }=t||{},a=o&&o[0]||{};elLoc.textContent=e||'—',elTemp.textContent=n?Math.round(n.temp)+'°F':'—',elCond.textContent=a.description?a.description.replace(/\b\w/g,t=>t.toUpperCase()):'—',a.icon?(elIcon.src=`https://openweathermap.org/img/wn/${a.icon}@2x.png`,elIcon.alt=a.main||''):(elIcon.removeAttribute('src'),elIcon.alt=''),themeByWeather(a.main),fxByWeather(a.main)}
function themeByWeather(t){const e=document.documentElement,n={Clear:{bg:'#fff8e1',fg:'#0f172a',panel:'#ffffffcc',primary:'#fde68a',tileBG:'#2b2b2f',tileFG:'#fff'},Clouds:{bg:'#f3f4f6',fg:'#111827',panel:'#ffffffcc',primary:'#9ca3af',tileBG:'#374151',tileFG:'#e5e7eb'},Rain:{bg:'#e5f2ff',fg:'#0f172a',panel:'#ffffffcc',primary:'#93c5fd',tileBG:'#1f2937',tileFG:'#ecfeff'},Drizzle:{bg:'#e5f2ff',fg:'#0f172a',panel:'#ffffffcc',primary:'#93c5fd',tileBG:'#1f2937',tileFG:'#ecfeff'},Thunderstorm:{bg:'#e9e7ff',fg:'#0f172a',panel:'#ffffffcc',primary:'#a5b4fc',tileBG:'#111827',tileFG:'#e5e7eb'},Snow:{bg:'#f8fafc',fg:'#0f172a',panel:'#ffffffcc',primary:'#cbd5e1',tileBG:'#334155',tileFG:'#f8fafc'},Mist:{bg:'#f1f5f9',fg:'#0f172a',panel:'#ffffffcc',primary:'#cbd5e1',tileBG:'#475569',tileFG:'#e5e7eb'},Fog:{bg:'#f1f5f9',fg:'#0f172a',panel:'#ffffffcc',primary:'#cbd5e1',tileBG:'#475569',tileFG:'#e5e7eb'},Haze:{bg:'#fef9c3',fg:'#0f172a',panel:'#ffffffcc',primary:'#f59e0b',tileBG:'#3f3f46',tileFG:'#fafaf9'}}[t]||{bg:'#ffffff',fg:'#101113',panel:'#ffffffcc',primary:'#e5e7eb',tileBG:'#2b2b2f',tileFG:'#ffffff'};e.style.setProperty('--bg',n.bg),e.style.setProperty('--fg',n.fg),e.style.setProperty('--panel',n.panel),e.style.setProperty('--primary',n.primary),e.style.setProperty('--tile-bg',n.tileBG),e.style.setProperty('--tile-fg',n.tileFG)}
const canvas=document.getElementById('fx'),ctx=canvas.getContext('2d');let fxType='None',particles=[],flashAlpha=0;function resizeCanvas(){canvas.width=canvas.clientWidth,canvas.height=canvas.clientHeight}
(new ResizeObserver(resizeCanvas)).observe(document.querySelector('.container')),resizeCanvas();
function fxClear(){particles=[],fxType='None',flashAlpha=0,ctx.clearRect(0,0,canvas.width,canvas.height)}
function fxSnow(){fxType='Snow',particles=Array.from({length:140},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:Math.random()*2+1,v:Math.random()*.6+.4}))}
function fxRain(){fxType='Rain',particles=Array.from({length:160},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,l:Math.random()*18+12,v:Math.random()*3+3}))}
function fxClouds(){fxType='Clouds',particles=Array.from({length:8},()=>({x:Math.random()*canvas.width,y:60+Math.random()*120,w:120+Math.random()*160,h:40+Math.random()*20,s:.2+.25*Math.random(),o:.12+.08*Math.random()}))}
function fxFog(){fxType='Fog',particles=Array.from({length:6},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,w:canvas.width*1.2,h:120,o:.05+.08*Math.random(),s:.2+.2*Math.random()}))}
function fxSun(){fxType='Sun',particles=Array.from({length:12},(_,t)=>({angle:Math.PI*2/12*t}))}
function fxByWeather(t){'Snow'===t?fxSnow():'Rain'===t||'Drizzle'===t?fxRain():'Thunderstorm'===t?(fxRain(),flashAlpha=.8):'Clouds'===t?fxClouds():'Mist'===t||'Fog'===t?fxFog():'Clear'===t?fxSun():fxClear()}
function animate(){requestAnimationFrame(animate),ctx.clearRect(0,0,canvas.width,canvas.height);if('Snow'===fxType){ctx.fillStyle='rgba(255,255,255,0.9)',particles.forEach(t=>{ctx.beginPath(),ctx.arc(t.x,t.y,t.r,0,2*Math.PI),ctx.fill(),t.y+=t.v,t.x+=Math.sin(t.y*.01)*.3,t.y>canvas.height&&(t.y=-5,t.x=Math.random()*canvas.width)})}else if('Rain'===fxType){ctx.strokeStyle='rgba(180,200,255,0.7)',ctx.lineWidth=1.2,particles.forEach(t=>{ctx.beginPath(),ctx.moveTo(t.x,t.y),ctx.lineTo(t.x+2,t.y+t.l),ctx.stroke(),t.y+=4*t.v,t.x+=1.2,t.y>canvas.height&&(t.y=-20,t.x=Math.random()*canvas.width)}),flashAlpha&&(ctx.fillStyle='rgba(255,255,255,'+flashAlpha+')',ctx.fillRect(0,0,canvas.width,canvas.height),flashAlpha-=.04,flashAlpha<0&&(flashAlpha=0),Math.random()<.02&&(flashAlpha=.8))}else if('Clouds'===fxType){particles.forEach(t=>{ctx.fillStyle='rgba(255,255,255,'+t.o+')';for(let e=-2;e<3;e++){ctx.beginPath();ctx.ellipse(t.x+e*20,t.y, t.w*.18,t.h*.6,0,0,Math.PI*2);ctx.fill()}t.x+=t.s,t.x- t.w>canvas.width&&(t.x=-t.w)})}else if('Fog'===fxType){particles.forEach(t=>{const e=ctx.createLinearGradient(0,t.y,0,t.y+t.h);e.addColorStop(0,'rgba(200,210,220,'+t.o+')'),e.addColorStop(1,'rgba(200,210,220,0)'),ctx.fillStyle=e,ctx.fillRect(t.x-200,t.y-40,t.w,t.h),t.x+=t.s,t.x>canvas.width+200&&(t.x=-200)})}else if('Sun'===fxType){const t=canvas.width-120,e=120,n=60,o=ctx.createRadialGradient(t,e,10,t,e,2*n);o.addColorStop(0,'rgba(255,220,90,0.9)'),o.addColorStop(1,'rgba(255,220,90,0.0)'),ctx.fillStyle=o,ctx.beginPath(),ctx.arc(t,e,2*n,0,2*Math.PI),ctx.fill(),ctx.strokeStyle='rgba(255,200,80,0.65)',ctx.lineWidth=3;const a=.001*Date.now();for(let r=0;r<12;r++){const i=a+Math.PI*2/12*r,s=t+Math.cos(i)*n,l=e+Math.sin(i)*n,c=t+Math.cos(i)*(n+22),h=e+Math.sin(i)*(n+22);ctx.beginPath(),ctx.moveTo(s,l),ctx.lineTo(c,h),ctx.stroke()}}}
animate();
async function load(t){input.value=t,setStatus('Fetching weather…','warn');try{const e=await fetchWeatherByZip(t);applyWeather(e),setStatus(`Updated for ${t}`,'ok')}catch(t){console.error(t),handleError(t)}}
function handleError(t){'NO_KEY'===t.message?setStatus('Add your OpenWeatherMap key in config.js (window.WEATHER_API_KEY = "...").','err'):401===t.httpStatus?setStatus('Invalid API key (401). Check config.js or wait for activation.','err'):404===t.httpStatus?setStatus('ZIP not found (404). Try another 5‑digit ZIP.','err'):429===t.httpStatus?setStatus('Rate limited (429). Please wait and try again.','err'):setStatus('Could not fetch weather. Network or CORS error.','err'),elLoc.textContent='—',elTemp.textContent='—',elCond.textContent='—',elIcon.removeAttribute('src'),elIcon.alt='',fxClear()}
form.addEventListener('submit',t=>{t.preventDefault();const e=(input.value||'').trim();if(!/^\d{5}$/.test(e))return input.focus(),void setStatus('Please enter a 5‑digit ZIP.','err');saveZip(e),load(e)});
geoBtn.addEventListener('click',()=>{if(!navigator.geolocation)return void setStatus('Geolocation not supported in this browser.','err');setStatus('Locating…','warn'),navigator.geolocation.getCurrentPosition(async t=>{const{ latitude:e,longitude:n }=t.coords;try{const t=await fetchWeatherByCoords(e,n);applyWeather(t),setStatus('Updated for your location','ok')}catch(t){console.error(t),handleError(t)}},t=>{setStatus('Location permission denied.','err')},{enableHighAccuracy:!1,timeout:8e3,maximumAge:6e4})});
setInterval(()=>load(loadZip()),REFRESH_MS);
function toggleFullscreen(){const t=document.documentElement;document.fullscreenElement?(document.exitFullscreen?.(),t.classList.remove('fullscreen'),fullscreenBtn.textContent='⛶ Full screen'):(document.documentElement.requestFullscreen?.(),t.classList.add('fullscreen'),fullscreenBtn.textContent='⛶ Exit full screen')}
fullscreenBtn.addEventListener('click',toggleFullscreen);
themeBtn.addEventListener('click',()=>{const t=document.documentElement;t.classList.toggle('dark'),themeBtn.textContent=t.classList.contains('dark')?'☀️ Light mode':'🌙 Dark mode'});
const initialZip=loadZip();load(initialZip);
