/* v3 app with status + cache-bust */
const STORAGE_KEY='weather_flip_zip';const REFRESH_MS=10*60*1000;const DEFAULT_ZIP='10001';
window.setupClock=function(tick){const p=v=>String(v).padStart(2,'0');const u=()=>{const n=new Date();tick.value=[p(n.getHours()),p(n.getMinutes()),p(n.getSeconds())];const sr=document.getElementById('sr-time');if(sr) sr.textContent=tick.value.join(':');};u();Tick.helper.interval(u,1000);};
const elLoc=document.getElementById('location'),elTemp=document.getElementById('temp'),elCond=document.getElementById('condition'),elIcon=document.getElementById('icon'),form=document.getElementById('zipForm'),input=document.getElementById('zipInput'),statusEl=document.getElementById('status'),fullscreenBtn=document.getElementById('fullscreenBtn');
const setStatus=(m,c='')=>{statusEl.className='status '+c;statusEl.textContent=m||'';};
function saveZip(z){try{localStorage.setItem(STORAGE_KEY,z);}catch{}}
function loadZip(){try{return localStorage.getItem(STORAGE_KEY)||DEFAULT_ZIP;}catch{return DEFAULT_ZIP;}}
async function fetchWeatherByZip(zip){if(!window.WEATHER_API_KEY) throw new Error('NO_KEY'); const url=`https://api.openweathermap.org/data/2.5/weather?zip=${encodeURIComponent(zip)},US&appid=${window.WEATHER_API_KEY}&units=imperial`; const res=await fetch(url); if(!res.ok){const t=await res.text();const e=new Error('HTTP_'+res.status);e.httpStatus=res.status;e.body=t;throw e;} return res.json();}
function applyWeather(d){const {name,main,weather}=d||{};const w=(weather&&weather[0])||{};elLoc.textContent=name||'—';elTemp.textContent=main?Math.round(main.temp)+'°F':'—';elCond.textContent=w.description?w.description.replace(/\b\w/g,c=>c.toUpperCase()):'—'; if(w.icon){elIcon.src=`https://openweathermap.org/img/wn/${w.icon}@2x.png`;elIcon.alt=w.main||'';}else{elIcon.removeAttribute('src');elIcon.alt='';} themeByWeather(w.main);}
function themeByWeather(main){const r=document.documentElement;const map={Clear:['#fff8e1','#0f172a','#fde68a'],Clouds:['#f3f4f6','#111827','#9ca3af'],Rain:['#e5f2ff','#0f172a','#93c5fd'],Drizzle:['#e5f2ff','#0f172a','#93c5fd'],Thunderstorm:['#e9e7ff','#0f172a','#a5b4fc'],Snow:['#f8fafc','#0f172a','#cbd5e1'],Mist:['#f1f5f9','#0f172a','#cbd5e1'],Fog:['#f1f5f9','#0f172a','#cbd5e1'],Haze:['#f8fafc','#0f172a','#eab308']}; const c=map[main]||['#ffffff','#101113','#e5e7eb']; r.style.setProperty('--bg',c[0]);r.style.setProperty('--fg',c[1]);r.style.setProperty('--panel','#ffffffcc');r.style.setProperty('--primary',c[2]);r.style.setProperty('--ring','rgba(14,165,233,0.35)');}
async function load(zip){input.value=zip;setStatus('Fetching weather…','warn');try{const d=await fetchWeatherByZip(zip);applyWeather(d);setStatus(`Updated for ${zip}`,'ok');}catch(err){console.error(err); if(err.message==='NO_KEY'){setStatus('Add your OpenWeatherMap key in config.js (window.WEATHER_API_KEY = ...).','err');} else if(err.httpStatus===401){setStatus('Invalid API key (401) or not yet active.','err');} else if(err.httpStatus===404){setStatus('ZIP not found (404).','err');} else if(err.httpStatus===429){setStatus('Rate limited (429).','err');} else {setStatus('Could not fetch weather. Network/CORS.','err');} elLoc.textContent='—';elTemp.textContent='—';elCond.textContent='—';elIcon.removeAttribute('src');elIcon.alt='';themeByWeather(null);}}
form.addEventListener('submit',e=>{e.preventDefault();const z=(input.value||'').trim();if(!/^\d{5}$/.test(z)){input.focus();setStatus('Please enter a 5‑digit ZIP.','err');return;} saveZip(z);load(z);});
setInterval(()=>load(loadZip()),REFRESH_MS);
function toggleFullscreen(){const r=document.documentElement;if(!document.fullscreenElement){document.documentElement.requestFullscreen?.();r.classList.add('fullscreen');fullscreenBtn.textContent='⛶ Exit full screen';}else{document.exitFullscreen?.();r.classList.remove('fullscreen');fullscreenBtn.textContent='⛶ Full screen';}}
fullscreenBtn.addEventListener('click',toggleFullscreen);
const initialZip=loadZip();load(initialZip);
