name: Deploy Fasting Tracker (Vite → GitHub Pages)

on:
  push:
    branches: [ main ]
    paths:
      - 'Fasting-Tracker/**'
      - '.github/workflows/deploy-fasting-tracker.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        working-directory: Fasting-Tracker
        run: npm ci || npm install

      - name: Build
        working-directory: Fasting-Tracker
        run: npm run build

      # Put the built app under a subfolder, and add a root redirect
      - name: Prepare Pages artifact with subfolder + root redirect
        run: |
          rm -rf public
          mkdir -p "public/Fasting-Tracker"
          cp -r "Fasting-Tracker/dist/." "public/Fasting-Tracker/"

          # Root redirect to /Webapps/Fasting-Tracker/
          cat > public/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=/Webapps/Fasting-Tracker/">
          <link rel="canonical" href="/Webapps/Fasting-Tracker/">
          <title>Redirecting…</title>
          <p>Redirecting to <a href="/Webapps/Fasting-Tracker/">/Webapps/Fasting-Tracker/</a></p>
          HTML

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
